import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

type TokenMap = { readonly [key: string]: unknown };

interface TokenSource {
  readonly label: string;
  readonly path: string;
}

interface RokuToken {
  readonly key: string;
  readonly name: string;
}

const outputPath = "source/DesignTokens.brs";

const rokuTokens: readonly RokuToken[] = [
  { name: "appBackground", key: "color.neutral.dark.bg" },
  { name: "appBackgroundWash", key: "surface.dark.listItemBg" },
  { name: "border", key: "color.neutral.dark.border" },
  { name: "borderHover", key: "color.neutral.dark.borderHover" },
  { name: "buttonFocus", key: "color.neutral.dark.componentBgActive" },
  { name: "buttonSurface", key: "color.neutral.dark.componentBg" },
  { name: "danger", key: "color.red.dark.solid" },
  { name: "dangerFocused", key: "color.red.dark.solidHover" },
  { name: "disabledText", key: "color.neutral.dark.solid" },
  { name: "focus", key: "color.neutral.dark.componentBgActive" },
  { name: "panelBorder", key: "color.neutral.dark.borderHover" },
  { name: "primary", key: "color.brand.yellow" },
  { name: "primaryPressed", key: "color.brand.yellow" },
  { name: "scrim", key: "surface.dark.overlayFull" },
  { name: "secondary", key: "color.neutral.dark.componentBg" },
  { name: "shadow", key: "surface.dark.overlayInline" },
  { name: "surface", key: "color.neutral.dark.componentBg" },
  { name: "text", key: "color.neutral.dark.text" },
  { name: "textInverse", key: "component.button.primary.foreground" },
  { name: "textMuted", key: "color.neutral.dark.textSecondary" },
  { name: "transparent", key: "surface.dark.listItemBg" },
];

export async function generateRokuDesign(repoRoot: string): Promise<string> {
  const tokenSource = resolveTokenSource(repoRoot);
  const tokens = await readTokenMap(tokenSource.path);
  const output = renderDesignTokens(
    rokuTokens.map((token) => ({
      name: token.name,
      value: toRokuColor(readTokenValue(tokens, token)),
    })),
    tokenSource.label,
  );
  const destination = resolve(repoRoot, outputPath);
  await mkdir(dirname(destination), { recursive: true });
  await writeFile(destination, output);

  return destination;
}

export function renderDesignTokens(
  tokens: readonly { readonly name: string; readonly value: string }[],
  sourcePath: string,
): string {
  const lines = [
    "' Generated by scripts/generate-roku-design.ts. Do not edit directly.",
    `' Source: ${sourcePath}`,
    "function designTokenColor(name as string) as string",
    "    colors = {",
  ];

  for (const token of tokens) {
    lines.push(`        ${token.name}: "${token.value}",`);
  }

  lines.push(
    "    }",
    "",
    "    if colors.doesExist(name)",
    "        return colors[name]",
    "    end if",
    "",
    "    return colors.text",
    "end function",
    "",
  );

  return lines.join("\n");
}

export function toRokuColor(value: string): string {
  const normalized = value.trim();
  const namedColor = namedColorToRokuColor(normalized);
  if (namedColor !== undefined) {
    return namedColor;
  }

  const hexMatch = /^#([0-9a-f]{3}|[0-9a-f]{6})$/i.exec(normalized);
  if (hexMatch !== null) {
    const raw = hexMatch[1];
    if (raw === undefined) {
      throw new Error(`Unsupported color value: ${value}`);
    }

    const expanded = raw.length === 3
      ? raw.split("").map((part) => `${part}${part}`).join("")
      : raw;
    return `0x${expanded.toUpperCase()}FF`;
  }

  const rgbaMatch = /^rgba\(\s*(\d+),\s*(\d+),\s*(\d+),\s*(0|1|0?\.\d+)\s*\)$/i.exec(normalized);
  if (rgbaMatch !== null) {
    const red = parseChannel(rgbaMatch[1], value);
    const green = parseChannel(rgbaMatch[2], value);
    const blue = parseChannel(rgbaMatch[3], value);
    const alpha = Math.round(Number(rgbaMatch[4]) * 255);
    return `0x${toHex(red)}${toHex(green)}${toHex(blue)}${toHex(alpha)}`;
  }

  const hslMatch = /^hsla?\(\s*([0-9.]+)(?:deg)?(?:\s*,\s*|\s+)([0-9.]+)%(?:\s*,\s*|\s+)([0-9.]+)%(?:(?:\s*,\s*|\s*\/\s*)(0|1|0?\.\d+))?\s*\)$/i.exec(normalized);
  if (hslMatch !== null) {
    const hue = Number(hslMatch[1]);
    const saturation = Number(hslMatch[2]) / 100;
    const lightness = Number(hslMatch[3]) / 100;
    const alpha = hslMatch[4] === undefined ? 255 : Math.round(Number(hslMatch[4]) * 255);
    const { red, green, blue } = hslToRgb(hue, saturation, lightness);
    return `0x${toHex(red)}${toHex(green)}${toHex(blue)}${toHex(alpha)}`;
  }

  throw new Error(`Unsupported color value: ${value}`);
}

function namedColorToRokuColor(value: string): string | undefined {
  switch (value.toLowerCase()) {
    case "black":
      return "0x000000FF";
    case "transparent":
      return "0x00000000";
    case "white":
      return "0xFFFFFFFF";
    default:
      return undefined;
  }
}

function hslToRgb(hue: number, saturation: number, lightness: number): { readonly blue: number; readonly green: number; readonly red: number } {
  if (!Number.isFinite(hue) || !Number.isFinite(saturation) || !Number.isFinite(lightness)) {
    throw new Error("Unsupported HSL color value");
  }

  const normalizedHue = ((hue % 360) + 360) % 360;
  const chroma = (1 - Math.abs(2 * lightness - 1)) * saturation;
  const huePrime = normalizedHue / 60;
  const x = chroma * (1 - Math.abs((huePrime % 2) - 1));
  const match = lightness - chroma / 2;
  let red = 0;
  let green = 0;
  let blue = 0;

  if (huePrime >= 0 && huePrime < 1) {
    red = chroma;
    green = x;
  } else if (huePrime >= 1 && huePrime < 2) {
    red = x;
    green = chroma;
  } else if (huePrime >= 2 && huePrime < 3) {
    green = chroma;
    blue = x;
  } else if (huePrime >= 3 && huePrime < 4) {
    green = x;
    blue = chroma;
  } else if (huePrime >= 4 && huePrime < 5) {
    red = x;
    blue = chroma;
  } else {
    red = chroma;
    blue = x;
  }

  return {
    blue: Math.round((blue + match) * 255),
    green: Math.round((green + match) * 255),
    red: Math.round((red + match) * 255),
  };
}

function resolveTokenSource(repoRoot: string): TokenSource {
  const explicitPath = process.env.PUTIO_DESIGN_TOKENS_PATH;
  if (explicitPath !== undefined && explicitPath !== "") {
    return {
      label: "PUTIO_DESIGN_TOKENS_PATH",
      path: resolve(repoRoot, explicitPath),
    };
  }

  try {
    return {
      label: "@putdotio/design/tokens",
      path: fileURLToPath(import.meta.resolve("@putdotio/design/tokens")),
    };
  } catch (error) {
    throw new Error(
      "Could not resolve @putdotio/design/tokens. Install or update @putdotio/design.",
      { cause: error },
    );
  }
}

async function readTokenMap(tokenPath: string): Promise<TokenMap> {
  const parsed = JSON.parse(await readFile(tokenPath, "utf8"));
  if (!isObject(parsed)) {
    throw new Error(`Expected token map object in ${tokenPath}`);
  }

  return parsed;
}

function readTokenValue(tokens: TokenMap, token: RokuToken): string {
  const entry = tokens[token.key];
  if (isObject(entry) && typeof entry.value === "string") {
    return entry.value;
  }

  throw new Error(`Missing required design token: ${token.key}`);
}

function parseChannel(value: string | undefined, source: string): number {
  if (value === undefined) {
    throw new Error(`Unsupported color value: ${source}`);
  }

  const channel = Number(value);
  if (!Number.isInteger(channel) || channel < 0 || channel > 255) {
    throw new Error(`Unsupported color channel in ${source}`);
  }

  return channel;
}

function toHex(channel: number): string {
  return channel.toString(16).padStart(2, "0").toUpperCase();
}

function isObject(value: unknown): value is TokenMap {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

async function main(): Promise<void> {
  const output = await generateRokuDesign(process.cwd());
  console.log(`Generated ${output}`);
}

if (process.argv[1] !== undefined && process.argv[1].endsWith("generate-roku-design.ts")) {
  await main();
}
